title: MaScFotografie
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1799631600733846
  brandStrength: 0.6600429
  lightness: 0.8243685835041106
  brandColors:
    - '#FFFFFF'
    - '#626258'
    - '#362013'
    - '#AFA8A0'
    - '#F1DECE'
  rhythmicContrast: 0.9445158985909075
typography_spectrum: 0.3485499
description: >-
  "My job as a portrait photographer is to seduce, amuse and entertain" by
  Helmut Newton
layout_spectrum: 0.9833512
name: MaScFotografie
